// <auto-generated />
namespace IAAI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addLanding3Tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addLanding3Tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202304140246250_addLanding3Tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
